added the setup
WCanirinka/buble-sort-pr pull request #1
Opened 2019-11-19 21:34 UTC by Tresor11

2019-11-19 22:40 UTC, WCanirinka commented
We are submitting for review

2019-11-20 06:47 UTC, wathigo requested changes
## Changes Required 

Let's fix the issues pointed out in the comments :point_down:  

**After implementing the changes, submit another request for review**

_Happy Coding :computer:  
Reviewed by: **Simon Wathigo**_

2019-11-20 06:47 UTC, wathigo commented on file.rb
> +end
**[REQUIRED]**
* We should not use `#sort` method to implement bubble sort algorithm.
* We must implement the correct methodology for the bubble sort algorithm. Check out [this](https://www.geeksforgeeks.org/bubble-sort/). Check this too :point_down: 
![rec](https://user-images.githubusercontent.com/44072711/69215260-321ba200-0b37-11ea-8476-b67b09766c13.png)

2019-11-20 06:47 UTC, wathigo commented on file.rb
> +end
**[REQUIRED]**
* We Should not use inbuilt `#sort` method.
* Remember to raise an error in no block is given.

2019-11-20 17:22 UTC, WCanirinka commented
Requesting for a code review after the correcting the required changes

2019-11-20 18:43 UTC, stratospherique requested changes
### Great progress Team :clap: :clap: However, further changes needs to be made in order for us to approve your project. check :arrow_down: 

- **[REQUIRED]** Check the code comments below, and use the notes to refactor your methods.

- **[REQUIRED]** No debugging code (i.e remove commented code in your case)

### That's it :relaxed: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
_**Ahmed Mahfoudh**_

2019-11-20 18:43 UTC, stratospherique commented on file.rb
> +      if yield(array[a], array[a + 1]).positive?
- Calling this method raises the following error : `undefined local variable or method 'arr'`. :pray: fix it.

2019-11-20 18:43 UTC, stratospherique commented on file.rb
> +end
- Calling bubble_sort method as below returns nil. :pray: fix it
  ```ruby
   arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
   p bubble_sort(arr) # returns nil
  ```

2019-11-20 19:59 UTC, ebukaume approved these changes
Hi @WCanirinka :wave: 

**Nice job! You can go ahead and merge this branch.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-11-20 20:10 UTC, merged